-- CreateTable
CREATE TABLE `TipoIntegracao` (
    `TPIT_ID` TINYINT NOT NULL AUTO_INCREMENT,
    `TPIT_Nome` VARCHAR(50) NOT NULL,

    PRIMARY KEY (`TPIT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pais` (
    `PAIS_ID` TINYINT NOT NULL AUTO_INCREMENT,
    `PAIS_SufixoTelefonia` SMALLINT NOT NULL,
    `PAIS_Nome` VARCHAR(125) NOT NULL,
    `PAIS_Sigla` CHAR(5) NOT NULL,

    PRIMARY KEY (`PAIS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Estado` (
    `ESTD_ID` TINYINT NOT NULL AUTO_INCREMENT,
    `ESTD_Nome` VARCHAR(125) NOT NULL,
    `ESTD_Sigla` CHAR(5) NOT NULL,
    `PAIS_ID` TINYINT NOT NULL,

    PRIMARY KEY (`ESTD_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Cidade` (
    `CIDA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `CIDA_Nome` VARCHAR(125) NOT NULL,
    `ESTD_ID` TINYINT NOT NULL,

    PRIMARY KEY (`CIDA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Usuario` (
    `USUA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USUA_Nome` VARCHAR(125) NOT NULL,
    `HOTL_ID` INTEGER NULL,
    `USUA_Email` VARCHAR(125) NOT NULL,
    `USUA_Senha` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`USUA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Hotel` (
    `HOTL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOTL_Nome` VARCHAR(125) NOT NULL,
    `HOTL_IdentificacaoTributaria` VARCHAR(20) NOT NULL,
    `HOTL_AcumulaPontuacao` BOOLEAN NOT NULL,
    `HOTL_ConversaoPontos` DECIMAL(12, 2) NULL,

    PRIMARY KEY (`HOTL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelIntegracaoArquivo` (
    `HOIA_ID` TINYINT NOT NULL AUTO_INCREMENT,
    `HOTL_ID` INTEGER NOT NULL,
    `TPIT_ID` TINYINT NOT NULL,
    `HOIA_Diretorio` VARCHAR(255) NOT NULL,
    `HOIA_Credencial` VARCHAR(255) NOT NULL,
    `HOIA_Senha` VARCHAR(255) NOT NULL,
    `HOIA_EnderecoIntegracao` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`HOIA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelImagem` (
    `HOIM_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOTL_ID` INTEGER NOT NULL,
    `HOIM_NomeArquivo` VARCHAR(125) NOT NULL,
    `HOIM_GUIDArquivo` VARCHAR(255) NULL,
    `HOIM_Base64` LONGTEXT NULL,

    PRIMARY KEY (`HOIM_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelEndereco` (
    `HOEN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOTL_ID` INTEGER NOT NULL,
    `HOEN_Numero` INTEGER NOT NULL,
    `HOEN_Bairro` VARCHAR(125) NOT NULL,
    `CIDA_ID` INTEGER NOT NULL,

    PRIMARY KEY (`HOEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelQuarto` (
    `HOQT_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOTL_ID` INTEGER NOT NULL,
    `HOQT_Numero` INTEGER NOT NULL,
    `HOQT_ValorDiaria` DECIMAL(12, 2) NOT NULL,
    `HOQT_Ativo` BOOLEAN NOT NULL,

    PRIMARY KEY (`HOQT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelQuartoImagem` (
    `HOQI_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOQT_ID` INTEGER NOT NULL,
    `HOQI_NomeArquivo` VARCHAR(125) NOT NULL,
    `HOQI_GUIDArquivo` VARCHAR(255) NULL,
    `HOQI_Base64` LONGTEXT NULL,

    PRIMARY KEY (`HOQI_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HotelQuartoAgendamento` (
    `HOQA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HOQA_CheckIn` DATETIME(3) NOT NULL,
    `HOQA_CheckOut` DATETIME(3) NOT NULL,
    `HOQT_ID` INTEGER NOT NULL,
    `USUA_ID` INTEGER NOT NULL,

    PRIMARY KEY (`HOQA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `UsuarioHotelPontuacao` (
    `USUA_ID` INTEGER NOT NULL,
    `HOTL_ID` INTEGER NOT NULL,
    `USHP_Pontuacao` INTEGER NOT NULL,

    PRIMARY KEY (`USUA_ID`, `HOTL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Estado` ADD CONSTRAINT `Estado_PAIS_ID_fkey` FOREIGN KEY (`PAIS_ID`) REFERENCES `Pais`(`PAIS_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Cidade` ADD CONSTRAINT `Cidade_ESTD_ID_fkey` FOREIGN KEY (`ESTD_ID`) REFERENCES `Estado`(`ESTD_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Usuario` ADD CONSTRAINT `Usuario_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelIntegracaoArquivo` ADD CONSTRAINT `HotelIntegracaoArquivo_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelIntegracaoArquivo` ADD CONSTRAINT `HotelIntegracaoArquivo_TPIT_ID_fkey` FOREIGN KEY (`TPIT_ID`) REFERENCES `TipoIntegracao`(`TPIT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelImagem` ADD CONSTRAINT `HotelImagem_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelEndereco` ADD CONSTRAINT `HotelEndereco_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelEndereco` ADD CONSTRAINT `HotelEndereco_CIDA_ID_fkey` FOREIGN KEY (`CIDA_ID`) REFERENCES `Cidade`(`CIDA_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelQuarto` ADD CONSTRAINT `HotelQuarto_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelQuartoImagem` ADD CONSTRAINT `HotelQuartoImagem_HOQT_ID_fkey` FOREIGN KEY (`HOQT_ID`) REFERENCES `HotelQuarto`(`HOQT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelQuartoAgendamento` ADD CONSTRAINT `HotelQuartoAgendamento_HOQT_ID_fkey` FOREIGN KEY (`HOQT_ID`) REFERENCES `HotelQuarto`(`HOQT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HotelQuartoAgendamento` ADD CONSTRAINT `HotelQuartoAgendamento_USUA_ID_fkey` FOREIGN KEY (`USUA_ID`) REFERENCES `Usuario`(`USUA_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `UsuarioHotelPontuacao` ADD CONSTRAINT `UsuarioHotelPontuacao_USUA_ID_fkey` FOREIGN KEY (`USUA_ID`) REFERENCES `Usuario`(`USUA_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `UsuarioHotelPontuacao` ADD CONSTRAINT `UsuarioHotelPontuacao_HOTL_ID_fkey` FOREIGN KEY (`HOTL_ID`) REFERENCES `Hotel`(`HOTL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
